### PR TITLE
Fix syntax error in the getCharList function

### LINKED ISSUE #2956: [Bug] unsupported operand types
A number of live portals have the following error in the error log files:

> PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string - string in /var/www/html/ecdysis/portal/classes/KeyDataManager.php:58\nStack trace:\n#0 /var/www/html/ecdysis/portal/classes/KeyDataManager.php(43): KeyDataManager->getCharList()\n#1 /var/www/html/ecdysis/portal/ident/key-v1.php(46): KeyDataManager->getData()\n#2 {main}\n  thrown in /var/www/html/ecdysis/portal/classes/KeyDataManager.php on line 58'

### PR DESCRIPTION
**Pull request by Atticus29**
# Description

Closes #2956 .

Fixes syntax error in the getCharList function where $countMin was accidentally being included inside the string quote and was also not being explicitly type cast to a float first.

## Before

Screenshot 2025-10-07 at 11 46 34 PM

## After

Screenshot 2025-10-07 at 11 46 26 PM

# Pull Request Checklist:

# Pre-Approval

- [ ] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [x] Hotfixes should be branched off of the `master` branch and PR'd using the **merge** option (not squashed) into the `hotfix` branch.
- [ ] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [ ] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [x] There are no linter errors
- [ ] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [x] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
- [x] Comment which GitHub issue(s), if any does this PR address
    - #2956 
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge into the `hotfix` branch, remember to use the **merge** option (i.e., no squash).
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a merge from the `hotfix` branch into the `master` branch use the **squash & merge** option
  - [ ] a subsequent PR from `master` into `Development` should be made with the **merge** option (i.e., no squash).
  - [ ] **Immediately** delete the `hotfix` branch and create a new `hotfix` branch
  - [ ] increment the Symbiota version number in the symbase.php file and commit to the `hotfix` branch.
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

### CODE REVIEW

File: classes/KeyDataManager.php [hunk 1]
```diff
@@ -51,17 +51,17 @@ private function getCharList(){
...
-					GROUP BY tc.CID HAVING ((Count(tc.TID)) > $countMin)';
+				$sqlRev = 'SELECT tc.CID, Count(tc.TID) AS c FROM '.
+					'(SELECT DISTINCT tList.TID, d.CID FROM (' . $this->sql . ') AS tList INNER JOIN kmdescr d ON tList.TID = d.TID WHERE (d.CS <> "-")) AS tc '.
+					'GROUP BY tc.CID HAVING ((Count(tc.TID)) > ' . $countMin . ')';
 				$rs = $this->conn->query($sqlRev);
 				while($row = $rs->fetch_object()){
 					$charList[] = $row->CID;
 				}
-				$countMin = $countMin*0.9;
+				$countMin = (float)($countMin * 0.9);
```
Comment (NikitaSalikov) [inline classes/KeyDataManager.php]: Is it necessary to cast again? It should be type float already

File: classes/KeyDataManager.php [hunk 2]
```diff
@@ -186,7 +186,7 @@ public function getCharArr(){
...
```
Comment (NikitaSalikov) [inline classes/KeyDataManager.php]: Same as above

**Review by GregoryPost — APPROVED** [review]

File: classes/KeyDataManager.php (hunk 1 above)
Comment (Atticus29) [reply classes/KeyDataManager.php]: Removed the redundant one in 104f2f7f7.

File: classes/KeyDataManager.php (hunk 2 above)
Comment (Atticus29) [reply classes/KeyDataManager.php]: Removed the redundant one in 104f2f7f7.
