### PR TITLE
Closes #2064 Fixing String Number multiply

### LINKED ISSUE #2064: [bug] PHP warnings in lichen portal
[Tue Jan 14 02:52:30.783090 2025] [php:warn] [pid 60977] [client 162.158.167.136:25978] PHP Warning:  Undefined global variable $$IMAGE_ROOT_PATH in /var/www/html/lichen/portal/classes/GlossaryManager.php on line 35
[Tue Jan 14 02:52:30.783132 2025] [php:warn] [pid 60977] [client 162.158.167.136:25978] PHP Warning:  Undefined global variable $$IMAGE_ROOT_URL in /var/www/html/lichen/portal/classes/GlossaryManager.php on line 37

also when trying to access the image sort tab for genus _Adelolecia_, I think we're getting this error:

[Tue Jan 14 02:55:40.712917 2025] [php:error] [pid 61326] [client 139.99.160.195:52342] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string - int in /var/www/html/lichen/portal/classes/ImageLibrarySearch.php:48\nStack trace:\n#0 /var/www/html/lichen/portal/imagelib/search.php(322): ImageLibrarySearch->getImageArr('', '200')\n#1 {main}\n  thrown in /var/www/html/lichen/portal/classes/ImageLibrarySearch.php on line 48
[Tue Jan 14 02:56:04.353514 2025] [php:error] [pid 61345] [client 139.99.160.195:49604] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string - int in /var/www/html/lichen/portal/classes/ImageLibrarySearch.php:48\nStack trace:\n#0 /var/www/html/lichen/portal/imagelib/search.php(322): ImageLibrarySearch->getImageArr('', 200)\n#1 {main}\n  thrown in /var/www/html/lichen/portal/classes/ImageLibrarySearch.php on line 48

image

### PR DESCRIPTION
**Pull request by MuchQuak**
# Issues #2064

# Summary
Adds as is_numeric check on 'page' request variable so that the `$pageNumber` variable is alwasys a number

# Pull Request Checklist:

# Pre-Approval

- [x] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [x] Hotfixes should be branched off of the `master` branch and PR'd using the **merge** option (not squashed) into the `hotfix` branch.
- [x] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [x] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [x] There are no linter errors
- [x] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [x] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [x] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
- [x] Comment which GitHub issue(s), if any does this PR address
- [x] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge into the `hotfix` branch, remember to use the **merge** option (i.e., no squash).
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a merge from the `hotfix` branch into the `master` branch use the **squash & merge** option
  - [ ] a subsequent PR from `master` into `Development` should be made with the **merge** option (i.e., no squash).
  - [ ] **Immediately** delete the `hotfix` branch and create a new `hotfix` branch
  - [ ] increment the Symbiota version number in the symbase.php file and commit to the `hotfix` branch.
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

### CODE REVIEW

File: imagelib/search.php [hunk 1]
```diff
@@ -14,7 +14,7 @@
 $keywords = array_key_exists('keywords',$_REQUEST) ? $_REQUEST['keywords'] : '';
 $imageCount = isset($_REQUEST['imagecount']) ? $_REQUEST['imagecount'] : 'all';
 $imageType = isset($_REQUEST['imagetype']) ? filter_var($_REQUEST['imagetype'], FILTER_SANITIZE_NUMBER_INT) : 0;
-$pageNumber = array_key_exists('page', $_REQUEST) ? filter_var($_REQUEST['page'], FILTER_SANITIZE_NUMBER_INT) : 1;
+$pageNumber = array_key_exists('page', $_REQUEST) && is_numeric($_REQUEST['page'])? filter_var($_REQUEST['page'], FILTER_SANITIZE_NUMBER_INT) : 1;
```
Comment (themerekat) [inline imagelib/search.php]: Should there be a space before the ?

**Review by themerekat — CHANGES_REQUESTED** [review]

**Review by themerekat — APPROVED** [review]
