### PR TITLE
[3.2] bugfix - 2247 -  resource url disambiguation

### LINKED ISSUE #2247: [3.2] Cannot add an image via the URL in Media tab
From Mike S:

"Although I can now upload images directly, the URL entry function doesn’t seem to be working.

   In the past, we were able to link iNat observations and use an icon image.  The procedure was:

If you use iNaturalist, we have devised a way to link your iNat observation to the CCH2 collection record.  From the same Media tab, click "Enter URL."  In the "Thumbnail version" field, type this (good to have typed already in a text file): https://herbarium.sdsu.edu/iNat_Observ-Logo3-r6.jpg
Go to your iNat observation and copy the URL of that observation.  Paste this URL into the "Resource URL (required):" field, e.g.: https://www.inaturalist.org/observations/148258939
This procedure will place an icon and a link to your iNat observation on the CCH2 Public View.  

   So, now this doesn’t work; nothing appears.  "

I'm guessing that the URL input now checks to see if your URL is a jpg or mp3 or something, and when it doesn't find it (because it's just a link), it doesn't let the record be saved.

### PR DESCRIPTION
**Pull request by Atticus29**
# Description

This PR resolves #2247 . Per discussions on Teams with @MuchQuak and @themerekat, the best way to resolve the issue seemed to be guiding the end user to use source webpage instead of resource URL for the full inat entry URL. Resource URL should really coorespond to the media (e.g., large image) itself, warranting some change to the copy.

I noticed that swapping the order of the `if($isRemoteMedia)` and the `if(!$should_upload_file)` still seemed required for things to work as expected.

# Pull Request Checklist:

# Pre-Approval

- [x] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and PR'd using the **merge** option (not squashed) into the `hotfix` branch.
    - N/A
- [x] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [x] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [x] There are no linter errors
- [ ] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
    - N/A
- [x] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
    - N/A
- [x] Comment which GitHub issue(s), if any does this PR address
    - #2247 
- [x] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge into the `hotfix` branch, remember to use the **merge** option (i.e., no squash).
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a merge from the `hotfix` branch into the `master` branch use the **squash & merge** option
  - [ ] a subsequent PR from `master` into `Development` should be made with the **merge** option (i.e., no squash).
  - [ ] **Immediately** delete the `hotfix` branch and create a new `hotfix` branch
  - [ ] increment the Symbiota version number in the symbase.php file and commit to the `hotfix` branch.
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

### CODE REVIEW

File: classes/Media.php [hunk 1]
```diff
@@ -817,11 +817,13 @@ public static function add(array $post_arr, $storage = null, $file = null): void
 
 		//If no file is given and downloads from urls are enabled
 		if(!self::isValidFile($file)) {
-			if(!$should_upload_file) {
-				$file = self::parse_map_only_file($clean_post_arr);
-			} else if($isRemoteMedia) {
+			if($isRemoteMedia) {
```
Comment (MuchQuak) [inline classes/Media.php]: Things get problematic for the uploader if this order changes. Both functions should produce the same result but parse_map_only_file is more performant at the cost of maybe being wrong in some edge cases. This is because one is parse_map_only_file makes some assumptions about the mime/type based on the extension. This in some cases will have conflicts which is when we need to use getRemoteFileInfo as a last resort. If we upload a lot of files our server in this configuration would curl every single file which would be very bad for performance. I can draft up some changes to make this more clear. Also it should be noted that a file can be remote and uploadable hence the if else.

**Review by MuchQuak — CHANGES_REQUESTED** [review]
If you would like me to draft up the changes for the comment I made let me know otherwise the general solution I would take is have the function try to `parse_map_only_file` if no upload is occurring. If that fails, you may need to make `isValidFile` more strict to check this, then if the file is a remote resource and the file is still invalid then try to `getRemoteFileInfo`. If both fail the throw exception should be kept.

**Comment by Atticus29** [comment]
> If you would like me to draft up the changes for the comment I made let me know otherwise the general solution I would take is have the function try to `parse_map_only_file` if no upload is occurring. If that fails, you may need to make `isValidFile` more strict to check this, then if the file is a remote resource and the file is still invalid then try to `getRemoteFileInfo`. If both fail the throw exception should be kept.

Reverted in 72a4e07c0. I believe that @MuchQuak 's [https://github.com/BioKIC/Symbiota/pull/2279](https://github.com/BioKIC/Symbiota/pull/2279) resolves the issue that I was trying to fix in Media.php.

**Review by MuchQuak — APPROVED** [review]
