### PR TITLE
Hotfix 2024 08 07

### LINKED ISSUE #1471: Unable to merge records using the duplicate catalog number cleaning tool
In SEINet
See: https://help.symbiota.org/scp/tickets.php?id=3889

If you try to merge (yes, both boxes should be checked, which is how I attempted to merge):
image

You get these results:
image

I _was_ able to merge using the Duplicate matching tool in the occurrence editor (for a different record that had been giving the same issue previously).

### LINKED ISSUE #1584: [3.1] Add Sources in glossary does not save, gets an error
When you click Add Sources, add information, and try to save, you get this error:

image

### LINKED ISSUE #1598: Taxon replace function fails due foreign key constraint issue
Deleting and remapping taxa within lichen portal fails due to following error. 

image

Attempted to remap Cladonia confusa confusa [[268078](https://lichenportal.org/portal/taxa/taxonomy/taxoneditor.php?tid=268078)] to Cladonia confusa f. confusa R. Sant. [[141382](https://lichenportal.org/portal/taxa/taxonomy/taxoneditor.php?tid=141382)].

### PR DESCRIPTION
**Pull request by egbot**
Taxonomy Editor
- Add taxamaps table to data remapping functions when taxon is deleted or remapped. Resolves [issue #1598](https://github.com/BioKIC/Symbiota/issues/1598)
- Minor error fixes and adjustments to language file imports
Glossary Management 
- Fix issue associated within new sources failing to save when displaying all terms without a taxon group selected. Resolves [issue #1584](https://github.com/BioKIC/Symbiota/issues/1584) 
- Display all source definitions when taxon group is not selected
- Minor adjustments to language terms and misc code
Occurrence Cleaner - duplicate merge tool
- Replace catalog numbers as the unique identifier for duplicate cluster with numeric key, thus avoiding interference of target form element due to existence of space or period within catalog number. Resolves [issue #1471](https://github.com/BioKIC/Symbiota/issues/1471) 
- Internationize first submit button
- Add header and footer to cleaning page
Specimen Upload
- Remove display of Data Versioning Checkbox option for snapshot datasets. Batch import data versioning is only available for live managed collections.

# Pull Request Checklist:
# Pre-Approval

- [x] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [x] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
- [ ] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [x] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [x] There are no linter errors
- [ ] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [x] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
- [x] Comment which GitHub issue(s), if any does this PR address
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [x] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [x] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

### CODE REVIEW

**Comment by GregoryPost** [comment]
@egbot  - Just checking - should this be a hotfix to master or a PR to Development?

File: config/symbbase.php [hunk 1]
```diff
@@ -2,7 +2,7 @@
 header('X-Frame-Options: DENY');
 header('Cache-control: private'); // IE 6 FIX
 date_default_timezone_set('America/Phoenix');
-$CODE_VERSION = '3.0.33';
+$CODE_VERSION = '3.0.34';
```
Comment (MuchQuak) [inline config/symbbase.php:5]: Good to know this how we version hotfixes, in case I need to make any in the future

**Review by MuchQuak — APPROVED** [review]
Logically everything looks sound
